version: '3'
services:
  couchserver:
    container_name: CouchDbServerMega
    image: couchdb:latest
    restart: always
    ports:
      - "5984:5984"
    mem_limit: 2048m
    cpu_count: 8
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
        - ./dbdata:/opt/couchdb/data
        #- ./file.sh:/home/matte.sh
